### ISSUE TITLE
Skinny Bots Issue on 6.1 Update

### ISSUE THREAD

**Issue by Kingdemonic666** [snowl/LoLEnhancementSuite#60]
Like the title says, its not working on the last update.
![lolclient 2016-01-14 16-09-02-43](https://cloud.githubusercontent.com/assets/6070287/12333116/7ed8b37e-bad9-11e5-8715-9eb3afbf109e.png)

**Comment by snowl** [comment]
I won't be able to update until OCE gets the new champ select (since I'm unable to test some things due to the changes). Sorry!

**Comment by frostycpu** [comment]
I pushed a fix to the experimental branch. [here](https://github.com/snowl/LoLEnhancementSuite/commit/b28290e555665f3585c8ebb206af85bffeaafdc9)

Apparently the version of AbcSharp, LES uses, is unable to handle activations in a constructor (big sorry!). This is fixed in the version the experimental branch uses.
